### ISSUE TITLE
Docker mount issue

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/phylonext-ws#6]
Command error:
  docker: Error response from daemon: error while creating mount source path '/mnt/auto/scratch/mblissett/cloud-data/latest': mkdir /mnt/auto/scratch/mblissett/cloud-data/latest: file exists.

https://phylonext.gbif.org/run/339b5e67-e78d-46f3-8edd-a48bb9866ab8

**Comment by MattBlissett** [comment]
The monthly download link didn't work on 1 January. Is it working now?

**Comment by thomasstjerne** [comment]
Yes, it looks like its running!
